apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  namespace: final
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      serviceAccountName: clo835
      containers:
      - name: flask-app
        image: 129952717198.dkr.ecr.us-east-1.amazonaws.com/flask-app:latest
        ports:
          - containerPort: 81
        env:
          - name: BG_IMAGE_URL
            valueFrom:
              configMapKeyRef:
                name: flask-config
                key: BG_IMAGE_URL
          - name: GROUP_NAME
            valueFrom:
              configMapKeyRef:
                name: flask-config
                key: GROUP_NAME
          - name: GROUP_SLOGAN
            valueFrom:
              configMapKeyRef:
                name: flask-config
                key: GROUP_SLOGAN
          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                name: flask-config
                key: DB_HOST
          - name: DB_NAME
            valueFrom:
              configMapKeyRef:
                name: flask-config
                key: DB_NAME
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: webapp-secrets
                key: DB_USER
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: webapp-secrets
                key: DB_PASSWORD
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: webapp-secrets
                key: AWS_ACCESS_KEY_ID
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: webapp-secrets
                key: AWS_SECRET_ACCESS_KEY
